/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package virtualpiano;

import java.awt.event.KeyEvent;
import sun.audio.*;
import java.io.*;
import javax.swing.JOptionPane;
/**
 *
 * @author MHRJ
 */
public class piano extends javax.swing.JFrame {

    /**
     * Creates new form piano
     */
    public piano() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        D = new javax.swing.JButton();
        C = new javax.swing.JButton();
        F = new javax.swing.JButton();
        E = new javax.swing.JButton();
        A = new javax.swing.JButton();
        G = new javax.swing.JButton();
        B = new javax.swing.JButton();
        BB = new javax.swing.JButton();
        CM = new javax.swing.JButton();
        EB = new javax.swing.JButton();
        FM = new javax.swing.JButton();
        GM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        D.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        D.setText("D");
        D.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });
        D.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DKeyPressed(evt);
            }
        });
        getContentPane().add(D, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 60, 180));

        C.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        C.setText("C");
        C.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });
        C.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CKeyPressed(evt);
            }
        });
        getContentPane().add(C, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 60, 180));

        F.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        F.setText("F");
        F.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FActionPerformed(evt);
            }
        });
        F.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FKeyPressed(evt);
            }
        });
        getContentPane().add(F, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 60, 180));

        E.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        E.setText("E");
        E.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EActionPerformed(evt);
            }
        });
        E.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EKeyPressed(evt);
            }
        });
        getContentPane().add(E, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 60, 180));

        A.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        A.setText("A");
        A.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });
        A.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AKeyPressed(evt);
            }
        });
        getContentPane().add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 60, 180));

        G.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        G.setText("G");
        G.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        G.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GActionPerformed(evt);
            }
        });
        G.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                GKeyPressed(evt);
            }
        });
        getContentPane().add(G, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 60, 180));

        B.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        B.setText("B");
        B.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });
        B.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BKeyPressed(evt);
            }
        });
        getContentPane().add(B, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 60, 180));

        BB.setBackground(new java.awt.Color(0, 0, 0));
        BB.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        BB.setForeground(new java.awt.Color(255, 255, 255));
        BB.setText("BB");
        BB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BB.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBActionPerformed(evt);
            }
        });
        BB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BBKeyPressed(evt);
            }
        });
        getContentPane().add(BB, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 60, 120));

        CM.setBackground(new java.awt.Color(0, 0, 0));
        CM.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CM.setForeground(new java.awt.Color(255, 255, 255));
        CM.setText("C#");
        CM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CM.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        CM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMActionPerformed(evt);
            }
        });
        CM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CMKeyPressed(evt);
            }
        });
        getContentPane().add(CM, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 60, 120));

        EB.setBackground(new java.awt.Color(0, 0, 0));
        EB.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        EB.setForeground(new java.awt.Color(255, 255, 255));
        EB.setText("EB");
        EB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EB.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        EB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EBActionPerformed(evt);
            }
        });
        EB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EBKeyPressed(evt);
            }
        });
        getContentPane().add(EB, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 60, 120));

        FM.setBackground(new java.awt.Color(0, 0, 0));
        FM.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        FM.setForeground(new java.awt.Color(255, 255, 255));
        FM.setText("F#");
        FM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FM.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        FM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FMActionPerformed(evt);
            }
        });
        FM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FMKeyPressed(evt);
            }
        });
        getContentPane().add(FM, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 60, 120));

        GM.setBackground(new java.awt.Color(0, 0, 0));
        GM.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GM.setForeground(new java.awt.Color(255, 255, 255));
        GM.setText("G#");
        GM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GM.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        GM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GMActionPerformed(evt);
            }
        });
        GM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                GMKeyPressed(evt);
            }
        });
        getContentPane().add(GM, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 60, 120));

        setSize(new java.awt.Dimension(547, 375));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EBActionPerformed
        // TODO add your handling code here:
        InputStream iAudio;
        
        try{
            iAudio = new FileInputStream(new File ("D:\\School\\PBO\\VirtualPiano\\src\\virtualpiano\\eb.wav"));
            AudioStream iMusic = new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_EBActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        InputStream iAudio;
        
        try{
            iAudio = new FileInputStream(new File ("D:\\School\\PBO\\VirtualPiano\\src\\virtualpiano\\c.wav"));
            AudioStream iMusic = new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_CActionPerformed

    private void CKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_C){
            
            InputStream iAudio;
        
            try{
                iAudio = new FileInputStream(new File ("D:\\School\\PBO\\VirtualPiano\\src\\virtualpiano\\c.wav"));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_CKeyPressed

    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
        // TODO add your handling code here:
        InputStream iAudio;
        
        try{
            iAudio = new FileInputStream(new File ("D:\\School\\PBO\\VirtualPiano\\src\\virtualpiano\\d.wav"));
            AudioStream iMusic = new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_DActionPerformed

    private void EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EActionPerformed
        // TODO add your handling code here:
        InputStream iAudio;
        
        try{
            iAudio = new FileInputStream(new File ("D:\\School\\PBO\\VirtualPiano\\src\\virtualpiano\\e.wav"));
            AudioStream iMusic = new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_EActionPerformed

    private void FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FActionPerformed
        // TODO add your handling code here:
        InputStream iAudio;
        
        try{
            iAudio = new FileInputStream(new File ("D:\\School\\PBO\\VirtualPiano\\src\\virtualpiano\\f.wav"));
            AudioStream iMusic = new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_FActionPerformed

    private void GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GActionPerformed
        // TODO add your handling code here:
        InputStream iAudio;
        
        try{
            iAudio = new FileInputStream(new File ("D:\\School\\PBO\\VirtualPiano\\src\\virtualpiano\\g.wav"));
            AudioStream iMusic = new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_GActionPerformed

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        // TODO add your handling code here:
        InputStream iAudio;
        
        try{
            iAudio = new FileInputStream(new File ("D:\\School\\PBO\\VirtualPiano\\src\\virtualpiano\\a.wav"));
            AudioStream iMusic = new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_AActionPerformed

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
        // TODO add your handling code here:
        InputStream iAudio;
        
        try{
            iAudio = new FileInputStream(new File ("D:\\School\\PBO\\VirtualPiano\\src\\virtualpiano\\b.wav"));
            AudioStream iMusic = new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_BActionPerformed

    private void CMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMActionPerformed
        // TODO add your handling code here:
        InputStream iAudio;
        
        try{
            iAudio = new FileInputStream(new File ("D:\\School\\PBO\\VirtualPiano\\src\\virtualpiano\\cm.wav"));
            AudioStream iMusic = new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_CMActionPerformed

    private void FMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FMActionPerformed
        // TODO add your handling code here:
        InputStream iAudio;
        
        try{
            iAudio = new FileInputStream(new File ("D:\\School\\PBO\\VirtualPiano\\src\\virtualpiano\\fm.wav"));
            AudioStream iMusic = new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_FMActionPerformed

    private void GMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GMActionPerformed
        // TODO add your handling code here:
        InputStream iAudio;
        
        try{
            iAudio = new FileInputStream(new File ("D:\\School\\PBO\\VirtualPiano\\src\\virtualpiano\\gm.wav"));
            AudioStream iMusic = new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_GMActionPerformed

    private void BBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBActionPerformed
        // TODO add your handling code here:
        InputStream iAudio;
        
        try{
            iAudio = new FileInputStream(new File ("D:\\School\\PBO\\VirtualPiano\\src\\virtualpiano\\bb.wav"));
            AudioStream iMusic = new AudioStream(iAudio);
            AudioPlayer.player.start(iMusic);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_BBActionPerformed

    private void DKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_D){
            
            InputStream iAudio;
        
            try{
                iAudio = new FileInputStream(new File ("D:\\School\\PBO\\VirtualPiano\\src\\virtualpiano\\d.wav"));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_DKeyPressed

    private void EKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_E){
            
            InputStream iAudio;
        
            try{
                iAudio = new FileInputStream(new File ("D:\\School\\PBO\\VirtualPiano\\src\\virtualpiano\\e.wav"));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_EKeyPressed

    private void FKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_F){
            
            InputStream iAudio;
        
            try{
                iAudio = new FileInputStream(new File ("D:\\School\\PBO\\VirtualPiano\\src\\virtualpiano\\f.wav"));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_FKeyPressed

    private void GKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_G){
            
            InputStream iAudio;
        
            try{
                iAudio = new FileInputStream(new File ("D:\\School\\PBO\\VirtualPiano\\src\\virtualpiano\\g.wav"));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_GKeyPressed

    private void AKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_A){
            
            InputStream iAudio;
        
            try{
                iAudio = new FileInputStream(new File ("D:\\School\\PBO\\VirtualPiano\\src\\virtualpiano\\a.wav"));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_AKeyPressed

    private void BKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_B){
            
            InputStream iAudio;
        
            try{
                iAudio = new FileInputStream(new File ("D:\\School\\PBO\\VirtualPiano\\src\\virtualpiano\\b.wav"));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_BKeyPressed

    private void CMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CMKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_Q){
            
            InputStream iAudio;
        
            try{
                iAudio = new FileInputStream(new File ("D:\\School\\PBO\\VirtualPiano\\src\\virtualpiano\\cm.wav"));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_CMKeyPressed

    private void EBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EBKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_W){
            
            InputStream iAudio;
        
            try{
                iAudio = new FileInputStream(new File ("D:\\School\\PBO\\VirtualPiano\\src\\virtualpiano\\eb.wav"));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_EBKeyPressed

    private void FMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FMKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_E){
            
            InputStream iAudio;
        
            try{
                iAudio = new FileInputStream(new File ("D:\\School\\PBO\\VirtualPiano\\src\\virtualpiano\\fm.wav"));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_FMKeyPressed

    private void GMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GMKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_R){
            
            InputStream iAudio;
        
            try{
                iAudio = new FileInputStream(new File ("D:\\School\\PBO\\VirtualPiano\\src\\virtualpiano\\gm.wav"));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_GMKeyPressed

    private void BBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BBKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_T){
            
            InputStream iAudio;
        
            try{
                iAudio = new FileInputStream(new File ("D:\\School\\PBO\\VirtualPiano\\src\\virtualpiano\\bb.wav"));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_BBKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new piano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A;
    private javax.swing.JButton B;
    private javax.swing.JButton BB;
    private javax.swing.JButton C;
    private javax.swing.JButton CM;
    private javax.swing.JButton D;
    private javax.swing.JButton E;
    private javax.swing.JButton EB;
    private javax.swing.JButton F;
    private javax.swing.JButton FM;
    private javax.swing.JButton G;
    private javax.swing.JButton GM;
    // End of variables declaration//GEN-END:variables
}
